package games.mrlaki5.backgammon.Economy;

import games.mrlaki5.backgammon.R;

/**
 * Which rendered art a shop product wears.
 *
 * Rarity here is a material rather than a coloured bar: bronze, silver,
 * turquoise glaze, gold. The card a product sits on and the medallion it carries
 * are cast in the same one, so a legendary item is gold all the way through
 * instead of merely labelled legendary — and a player can read what something is
 * worth from across the screen, in this game's own terms.
 *
 * The art is generated by tools/generate_royal_assets.py.
 */
public final class ShopArt {

    private ShopArt() {}

    /** The plaque a product is mounted on. */
    public static int card(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.card_rare;
            case EPIC:      return R.drawable.card_epic;
            case LEGENDARY: return R.drawable.card_legendary;
            case COMMON:
            default:        return R.drawable.card_common;
        }
    }

    /**
     * The struck medallion for a product: its category chooses the mark, its
     * rarity chooses the metal.
     */
    public static int medallion(ShopItem.Category category, ShopItem.Rarity rarity) {
        switch (category) {
            case DICE_SKIN:    return dice(rarity);
            case TITLE:        return crown(rarity);
            case THEME:        return book(rarity);
            case AVATAR_FRAME: return medal(rarity);
            case COSMETIC:     return trophy(rarity);
            case CONSUMABLE:
            case BUNDLE:
            case ALL:
            default:           return shop(rarity);
        }
    }

    private static int dice(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_dice_rare;
            case EPIC:      return R.drawable.medal_dice_epic;
            case LEGENDARY: return R.drawable.medal_dice_legendary;
            default:        return R.drawable.medal_dice_common;
        }
    }

    private static int crown(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_crown_rare;
            case EPIC:      return R.drawable.medal_crown_epic;
            case LEGENDARY: return R.drawable.medal_crown_legendary;
            default:        return R.drawable.medal_crown_common;
        }
    }

    private static int book(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_book_rare;
            case EPIC:      return R.drawable.medal_book_epic;
            case LEGENDARY: return R.drawable.medal_book_legendary;
            default:        return R.drawable.medal_book_common;
        }
    }

    private static int medal(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_medal_rare;
            case EPIC:      return R.drawable.medal_medal_epic;
            case LEGENDARY: return R.drawable.medal_medal_legendary;
            default:        return R.drawable.medal_medal_common;
        }
    }

    private static int trophy(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_trophy_rare;
            case EPIC:      return R.drawable.medal_trophy_epic;
            case LEGENDARY: return R.drawable.medal_trophy_legendary;
            default:        return R.drawable.medal_trophy_common;
        }
    }

    private static int shop(ShopItem.Rarity rarity) {
        switch (rarity) {
            case RARE:      return R.drawable.medal_shop_rare;
            case EPIC:      return R.drawable.medal_shop_epic;
            case LEGENDARY: return R.drawable.medal_shop_legendary;
            default:        return R.drawable.medal_shop_common;
        }
    }
}
